name: Test and Build

on:
  push:
    branches:
      - 'main'
      - 'release/**'
      - 'feature/**'
      - 'fix/**'
      - 'chore/**'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Test, Coverage & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Setup Task (go-task/task)
        uses: tenthirtyam/setup-task@v1.0.5

      - name: Run Tests
        run: task test

      - name: Run Coverage
        run: task cover

      - name: Build Engine Binary
        run: task build
